// backend/models/doctorsData.js

const doctors = [
    {
      //_id: 'doc1',
      name: 'Dr. Richard James',
      email: 'richard.james@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-richard.jpg',
      speciality: 'General physician',
      degree: 'MBBS',
      experience: '4 Years',
      about: 'Dr. Richard James delivers comprehensive medical care with a focus on preventive medicine, early diagnosis, and effective treatment strategies.',
      available: true,
      fees: 50,
      slots_booked: {},
      address: { line1: '17th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
    //  _id: 'doc2',
      name: 'Dr. Emily Larson',
      email: 'emily.larson@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-emily.jpg',
      speciality: 'Gynecologist',
      degree: 'MBBS',
      experience: '3 Years',
      about: 'Dr. Emily Larson specializes in women’s health, providing compassionate care and advanced gynecological treatment.',
      available: true,
      fees: 60,
      slots_booked: {},
      address: { line1: '27th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc3',
      name: 'Dr. Sarah Patel',
      email: 'sarah.patel@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-sarah.jpg',
      speciality: 'Dermatologist',
      degree: 'MBBS',
      experience: '1 Year',
      about: 'Dr. Sarah Patel provides expert care for skin conditions, with a focus on both medical and cosmetic dermatology.',
      available: true,
      fees: 30,
      slots_booked: {},
      address: { line1: '37th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     //_id: 'doc4',
      name: 'Dr. John Williams',
      email: 'john.williams@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-john.jpg',
      speciality: 'Pediatricians',
      degree: 'MBBS',
      experience: '5 Years',
      about: 'Dr. John Williams is dedicated to providing exceptional medical care for children from infancy through adolescence.',
      available: true,
      fees: 45,
      slots_booked: {},
      address: { line1: '47th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc5',
      name: 'Dr. Ananya Gupta',
      email: 'ananya.gupta@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-ananya.jpg',
      speciality: 'Cardiologist',
      degree: 'MD (Cardiology)',
      experience: '7 Years',
      about: 'Dr. Ananya Gupta specializes in heart diseases, preventive cardiology, and advanced cardiac treatments.',
      available: true,
      fees: 100,
      slots_booked: {},
      address: { line1: '57th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc6',
      name: 'Dr. Michael Brown',
      email: 'michael.brown@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-michael.jpg',
      speciality: 'Orthopedic',
      degree: 'MS (Orthopedics)',
      experience: '6 Years',
      about: 'Dr. Michael Brown offers expert orthopedic care, including bone injuries, fractures, and joint replacements.',
      available: true,
      fees: 80,
      slots_booked: {},
      address: { line1: '67th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc7',
      name: 'Dr. Priya Sharma',
      email: 'priya.sharma@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-priya.jpg',
      speciality: 'Neurologist',
      degree: 'DM (Neurology)',
      experience: '8 Years',
      about: 'Dr. Priya Sharma provides diagnosis and treatment for brain, spine, and nerve disorders with a patient-centered approach.',
      available: true,
      fees: 120,
      slots_booked: {},
      address: { line1: '77th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc8',
      name: 'Dr. David Lee',
      email: 'david.lee@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-david.jpg',
      speciality: 'ENT Specialist',
      degree: 'MBBS, MS (ENT)',
      experience: '4 Years',
      about: 'Dr. David Lee specializes in treating conditions of the ear, nose, and throat with modern surgical techniques.',
      available: true,
      fees: 55,
      slots_booked: {},
      address: { line1: '87th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc9',
      name: 'Dr. Aisha Khan',
      email: 'aisha.khan@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-aisha.jpg',
      speciality: 'Psychiatrist',
      degree: 'MD (Psychiatry)',
      experience: '5 Years',
      about: 'Dr. Aisha Khan provides compassionate mental health care, focusing on therapy and medication management.',
      available: true,
      fees: 70,
      slots_booked: {},
      address: { line1: '97th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc10',
      name: 'Dr. Robert Taylor',
      email: 'robert.taylor@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-robert.jpg',
      speciality: 'Dentist',
      degree: 'BDS, MDS',
      experience: '3 Years',
      about: 'Dr. Robert Taylor is skilled in dental treatments, including cosmetic dentistry, root canals, and preventive care.',
      available: true,
      fees: 40,
      slots_booked: {},
      address: { line1: '107th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc11',
      name: 'Dr. Sneha Verma',
      email: 'sneha.verma@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-sneha.jpg',
      speciality: 'Oncologist',
      degree: 'DM (Oncology)',
      experience: '10 Years',
      about: 'Dr. Sneha Verma specializes in cancer treatment with chemotherapy, radiation, and targeted therapies.',
      available: true,
      fees: 150,
      slots_booked: {},
      address: { line1: '117th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc12',
      name: 'Dr. Daniel Evans',
      email: 'daniel.evans@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-daniel.jpg',
      speciality: 'Ophthalmologist',
      degree: 'MS (Ophthalmology)',
      experience: '6 Years',
      about: 'Dr. Daniel Evans provides advanced eye care, cataract surgeries, and laser vision correction.',
      available: true,
      fees: 75,
      slots_booked: {},
      address: { line1: '127th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc13',
      name: 'Dr. Kavya Reddy',
      email: 'kavya.reddy@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-kavya.jpg',
      speciality: 'Endocrinologist',
      degree: 'DM (Endocrinology)',
      experience: '9 Years',
      about: 'Dr. Kavya Reddy treats hormonal disorders including diabetes, thyroid, and metabolism-related issues.',
      available: true,
      fees: 110,
      slots_booked: {},
      address: { line1: '137th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
      //_id: 'doc14',
      name: 'Dr. William Scott',
      email: 'william.scott@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-william.jpg',
      speciality: 'Nephrologist',
      degree: 'DM (Nephrology)',
      experience: '12 Years',
      about: 'Dr. William Scott specializes in kidney-related diseases, dialysis, and transplant care.',
      available: true,
      fees: 130,
      slots_booked: {},
      address: { line1: '147th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    },
    {
     // _id: 'doc15',
      name: 'Dr. Sofia Martinez',
      email: 'sofia.martinez@example.com',
      password: 'hashedpassword123',
      image: 'https://example.com/dr-sofia.jpg',
      speciality: 'Gastroenterologist',
      degree: 'DM (Gastroenterology)',
      experience: '7 Years',
      about: 'Dr. Sofia Martinez provides expert care for digestive system disorders and advanced endoscopic procedures.',
      available: true,
      fees: 95,
      slots_booked: {},
      address: { line1: '157th Cross, Richmond', line2: 'Circle, Ring Road, London' },
      date: Date.now()
    }
  ];
  
  export default doctors;
  